Pg search
Bartducrot/hubert pull request #72
Opened 2017-06-13 19:07 UTC by chamyndu

2017-06-13 22:16 UTC, Bartducrot requested changes

2017-06-13 22:16 UTC, Bartducrot commented on app/assets/stylesheets/layout/_utilities.scss
> +.row {
@chamyndu ".row" is already a bootstrap class, you shouldn't override it here, use an other class name (it could break the bootstrap class)

2017-06-13 22:16 UTC, Bartducrot commented on app/views/users/show.html.erb
> +<div style="padding-top: 80px" class="container user-profile text-center">
@chamyndu why did you put a style attribute instead of using a class?

2017-06-13 23:09 UTC, chamyndu reviewed
I amended 2 things you pointed out and 1 thing I noticed when I was going through the change, adding "main-container" to the ingredients page

2017-06-14 09:59 UTC, Bartducrot approved these changes

2017-06-14 09:59 UTC, merged